export const TradeCoinPairAbi = [
  { stateMutability: "Nonpayable", type: "Constructor" },
  {
    inputs: [
      { indexed: true, name: "owner", type: "address" },
      { indexed: true, name: "spender", type: "address" },
      { name: "value", type: "uint256" },
    ],
    name: "Approval",
    type: "Event",
  },
  {
    inputs: [
      { indexed: true, name: "sender", type: "address" },
      { name: "amount0", type: "uint256" },
      { name: "amount1", type: "uint256" },
      { indexed: true, name: "to", type: "address" },
    ],
    name: "Burn",
    type: "Event",
  },
  {
    inputs: [
      { indexed: true, name: "sender", type: "address" },
      { name: "amount0", type: "uint256" },
      { name: "amount1", type: "uint256" },
    ],
    name: "Mint",
    type: "Event",
  },
  {
    inputs: [
      { indexed: true, name: "sender", type: "address" },
      { name: "amount0In", type: "uint256" },
      { name: "amount1In", type: "uint256" },
      { name: "amount0Out", type: "uint256" },
      { name: "amount1Out", type: "uint256" },
      { indexed: true, name: "to", type: "address" },
    ],
    name: "Swap",
    type: "Event",
  },
  {
    inputs: [
      { name: "reserve0", type: "uint112" },
      { name: "reserve1", type: "uint112" },
    ],
    name: "Sync",
    type: "Event",
  },
  {
    inputs: [
      { indexed: true, name: "from", type: "address" },
      { indexed: true, name: "to", type: "address" },
      { name: "value", type: "uint256" },
    ],
    name: "Transfer",
    type: "Event",
  },
  {
    outputs: [{ type: "bytes32" }],
    constant: true,
    name: "DOMAIN_SEPARATOR",
    stateMutability: "View",
    type: "Function",
  },
  {
    outputs: [{ type: "uint256" }],
    constant: true,
    name: "MINIMUM_LIQUIDITY",
    stateMutability: "View",
    type: "Function",
  },
  {
    outputs: [{ type: "bytes32" }],
    constant: true,
    name: "PERMIT_TYPEHASH",
    stateMutability: "View",
    type: "Function",
  },
  {
    outputs: [{ type: "uint256" }],
    constant: true,
    inputs: [{ type: "address" }, { type: "address" }],
    name: "allowance",
    stateMutability: "View",
    type: "Function",
  },
  {
    outputs: [{ type: "bool" }],
    inputs: [
      { name: "spender", type: "address" },
      { name: "value", type: "uint256" },
    ],
    name: "approve",
    stateMutability: "Nonpayable",
    type: "Function",
  },
  {
    outputs: [{ type: "uint256" }],
    constant: true,
    inputs: [{ type: "address" }],
    name: "balanceOf",
    stateMutability: "View",
    type: "Function",
  },
  {
    outputs: [
      { name: "amount0", type: "uint256" },
      { name: "amount1", type: "uint256" },
    ],
    inputs: [{ name: "to", type: "address" }],
    name: "burn",
    stateMutability: "Nonpayable",
    type: "Function",
  },
  {
    outputs: [{ type: "uint8" }],
    constant: true,
    name: "decimals",
    stateMutability: "View",
    type: "Function",
  },
  {
    outputs: [{ type: "address" }],
    constant: true,
    name: "factory",
    stateMutability: "View",
    type: "Function",
  },
  {
    outputs: [
      { name: "_reserve0", type: "uint112" },
      { name: "_reserve1", type: "uint112" },
      { name: "_blockTimestampLast", type: "uint32" },
    ],
    constant: true,
    name: "getReserves",
    stateMutability: "View",
    type: "Function",
  },
  {
    inputs: [
      { name: "_token0", type: "address" },
      { name: "_token1", type: "address" },
    ],
    name: "initialize",
    stateMutability: "Nonpayable",
    type: "Function",
  },
  {
    outputs: [{ type: "uint256" }],
    constant: true,
    name: "kLast",
    stateMutability: "View",
    type: "Function",
  },
  {
    outputs: [{ name: "liquidity", type: "uint256" }],
    inputs: [{ name: "to", type: "address" }],
    name: "mint",
    stateMutability: "Nonpayable",
    type: "Function",
  },
  {
    outputs: [{ type: "string" }],
    constant: true,
    name: "name",
    stateMutability: "View",
    type: "Function",
  },
  {
    outputs: [{ type: "uint256" }],
    constant: true,
    inputs: [{ type: "address" }],
    name: "nonces",
    stateMutability: "View",
    type: "Function",
  },
  {
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
      { name: "value", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "v", type: "uint8" },
      { name: "r", type: "bytes32" },
      { name: "s", type: "bytes32" },
    ],
    name: "permit",
    stateMutability: "Nonpayable",
    type: "Function",
  },
  {
    outputs: [{ type: "uint256" }],
    constant: true,
    name: "price0CumulativeLast",
    stateMutability: "View",
    type: "Function",
  },
  {
    outputs: [{ type: "uint256" }],
    constant: true,
    name: "price1CumulativeLast",
    stateMutability: "View",
    type: "Function",
  },
  {
    inputs: [{ name: "to", type: "address" }],
    name: "skim",
    stateMutability: "Nonpayable",
    type: "Function",
  },
  {
    inputs: [
      { name: "amount0Out", type: "uint256" },
      { name: "amount1Out", type: "uint256" },
      { name: "to", type: "address" },
      { name: "data", type: "bytes" },
    ],
    name: "swap",
    stateMutability: "Nonpayable",
    type: "Function",
  },
  {
    outputs: [{ type: "string" }],
    constant: true,
    name: "symbol",
    stateMutability: "View",
    type: "Function",
  },
  { name: "sync", stateMutability: "Nonpayable", type: "Function" },
  {
    outputs: [{ type: "address" }],
    constant: true,
    name: "token0",
    stateMutability: "View",
    type: "Function",
  },
  {
    outputs: [{ type: "address" }],
    constant: true,
    name: "token1",
    stateMutability: "View",
    type: "Function",
  },
  {
    outputs: [{ type: "uint256" }],
    constant: true,
    name: "totalSupply",
    stateMutability: "View",
    type: "Function",
  },
  {
    outputs: [{ type: "bool" }],
    inputs: [
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
    ],
    name: "transfer",
    stateMutability: "Nonpayable",
    type: "Function",
  },
  {
    outputs: [{ type: "bool" }],
    inputs: [
      { name: "from", type: "address" },
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
    ],
    name: "transferFrom",
    stateMutability: "Nonpayable",
    type: "Function",
  },
];
